creation_rules:
  - path_regex: host/desktop/secrets/[^/]+$
    key_group:
    age: "age1r9rat6azszlrg0v6784xmxlrrdxld7px8jth3mj6z776ww9uuvmqhfk8ay"
  - path_regex: host/surface/secrets/[^/]+$
    key_group:
    age: "age18a39ajm8ag8su9ue66vfh5yggwfx3yy787vf0hw77h2ucatv23ks76apdv"
