[General]
background=/home/philipp/Pictures/wallpaper/dgah3n6-87b58f18-df9d-427f-a7e5-51879c8978a0.jpg

fontFamily="JetBrainsMono NF"
# Blur radius for the background
blurRadius=0
# interface radius
radius=20

mPrimary=#fff59b
mOnPrimary=#0e0e43

mSecondary=#a9aefe
mOnSecondary=#0e0e43

mTertiary=#9bfece
mOnTertiary=#0e0e43

mError=#fd4663
mOnError=#0e0e43

mSurface=#070722
mOnSurface=#f3edf7

mSurfaceVariant=#11112d
mOnSurfaceVariant=#7c80b4

mOutline=#323291
mShadow=#070722

mHover=#9bfece
mOnHover=#0e0e43
