#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/git ~/uni-nextcloud ~/.config -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
selected_name=${selected_name}
tmux_running=$(pgrep tmux)

# if already open in other terminal, focus that terminal

~/.config/i3/scripts/navigate-to-window.py "$selected_name:" "Alacritty" && exit 0

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    # new-session [options] [shell-command]   shell-command will not execute in the shell, but REPLACE the shell
    tmux new-session -ds $selected_name -c "$selected"
    selected_name="$selected_name:1"
fi
tmux switch-client -t $selected_name
