{ pkgs, self, config, user, ... }:
{
  environment.systemPackages = with pkgs; [
    wget
    traceroute
    dig
    file
    killall
    whois
    nix-tree
    jq
    smartmontools
    tmux
    polkit
    gcc
    unzip
    fzf
    home-manager
    ripgrep
    xsel
    nix-index
    htop-vim
    self.nixvim
    man-pages
    nix-output-monitor
    lsof
    # https://github.com/aristocratos/btop/issues/426#issuecomment-2104289634
    (btop.override {cudaSupport = true;})
    config.boot.kernelPackages.usbip
  ] ++ lib.optionals config.home-manager.users.${user}.gui [
    kitty
    dconf
    xwayland
    firefox
    obsidian
    wl-clipboard
    discord
    tidal-hifi
    libsForQt5.qtstyleplugin-kvantum
    libsForQt5.qt5ct
    kdePackages.qt6ct
    kdePackages.qtstyleplugin-kvantum
    adwaita-icon-theme
    kdePackages.dolphin
    kdePackages.kde-cli-tools
    kdePackages.breeze
    kdePackages.breeze-icons
    kdePackages.qtwayland
    kdePackages.qtsvg
    kdePackages.kio-fuse
    kdePackages.kio-extras
    kdePackages.kdesdk-thumbnailers
    kdePackages.kdegraphics-thumbnailers
    kdePackages.ffmpegthumbs
    kdePackages.dolphin-plugins
    kdePackages.okular
    kdePackages.gwenview
    kdePackages.ark
    rar
    libsForQt5.kservice
    libsForQt5.qt5.qtgraphicaleffects
    thunderbird
    bazecor
    teamspeak6-client
    obs-studio
    sioyek
    qpwgraph
    rnote
    qbittorrent
    kdePackages.kolourpaint
    audacity
    kicad
    freecad
    openscad
    android-tools
  ];
}
